USE AdventureWorks2012; 
GO 
 
SELECT ProductID
FROM DBO.demoProduct
WHERE PRODUCTID>900

DELETE DBO.demoProduct
WHERE PRODUCTID>900

SELECT ProductID
FROM DBO.demoProduct
WHERE PRODUCTID>900