USE AdventureWorks2012; 
GO 
 

 -- Write an UPDATE statement that updates the SubTotal column of each row of the dbo.demoSalesOrderHeader table
 -- with the sum of the LineTotal column of the dbo.demoSalesOrderDemo table

SELECT SOH.SalesOrderID,SOH.SUBTOTAL,DOD.LINETOTAL
FROM DBO.DEMOSALESORDERHEADER AS SOH
JOIN DBO.DEMOSALESORDERDEMO1 AS DOD
ON SOH.SALESORDERID=DOD.SALESORDERID

UPDATE SOH
SET SOH.SUBTOTAL=DOD.LINETOTAL
FROM DBO.DEMOSALESORDERHEADER AS SOH
JOIN DBO.DEMOSALESORDERDEMO1 AS DOD
ON SOH.SALESORDERID=DOD.SALESORDERID

SELECT SOH.SalesOrderID,SOH.SUBTOTAL,DOD.LINETOTAL
FROM DBO.DEMOSALESORDERHEADER AS SOH
JOIN DBO.DEMOSALESORDERDEMO1 AS DOD
ON SOH.SALESORDERID=DOD.SALESORDERID